var Aristos = [ {Id:1, Name:"Mushashi", Image:"mushashi.png", expansion: 1},
{Id:2, Name:"Wild Bill", Image:"wild_bill.png", expansion: 1},
{Id:3, Name:"Gata", Image:"gata.png", expansion: 1},
{Id:4, Name:"Major Lunah", Image:"lunah.png", expansion: 1},
{Id:5, Name:"Hexx3r", Image:"hexx3r.png", expansion: 1},
{Id:6, Name:"Parvati", Image:"parvati.png", expansion: 1},
{Id:7, Name:"8-Ball", Image:"8ball.png", expansion: 1},
{Id:8, Name:"Maximus", Image:"maximus.png", expansion: 1},
{Id:9, Name:"Valkyrie", Image:"valkyrie.png", expansion: 2},
{Id:10, Name:"Hannibal", Image:"hannibal.png", expansion: 2},
{Id:11, Name:"Laxmee", Image:"laxmee.png", expansion: 2},
{Id:12, Name:"Señor Massacre", Image:"massacre.png", expansion: 2},
{Id:13, Name:"Padre Mendoza", Image:"mendoza.png", expansion: 3},
{Id:14, Name:"Murtair", Image:"murtair.png", expansion: 3},
{Id:15, Name:"Kozmo", Image:"kozmo.png", expansion: 3},
{Id:16, Name:"Taowu", Image:"taowu.png", expansion: 3},
{Id:17, Name:"Dart", Image:"dart.png", expansion: 4},
{Id:18, Name:"Bixie", Image:"bixie.png", expansion: 4},
{Id:19, Name:"Prysm", Image:"prysm.png", expansion: 4},
{Id:20, Name:"Eclypse", Image:"eclypse.png", expansion: 4},
{Id:21, Name:"Oberon", Image:"oberon.png", expansion: 5},
{Id:22, Name:"Shona Carano", Image:"shona.png", expansion: 5},
{Id:23, Name:"Reina Koorie", Image:"koorie.png", expansion: 5},
{Id:24, Name:"Final Boss", Image:"boss.png", expansion: 5} ,
{Id:25, Name:"Bachmann", Image:"bachmann.png", expansion: 6} ,
{Id:26, Name:"Hammerhead", Image:"hammerhead.png", expansion: 6} ,
{Id:27, Name:"Gaia", Image:"gaia.png", expansion: 7} ,
{Id:28, Name:"Fiddler", Image:"fiddler.png", expansion: 7} ,];

